//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBookingWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomType
    {
        public int RoomTypeId { get; set; }
        public string RoomTypeName { get; set; }
    }
}
